# Generated by Django 3.1.7 on 2021-03-21 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_libr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default='1998-06-08', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='readstatus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_created=True, default='2000-12-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='read_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
