# Generated by Django 3.1.7 on 2021-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_libr', '0002_auto_20210321_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, default='1998-08-06', null=True),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Planned'), ('C', 'Completed'), ('D', 'Dropped'), ('U', 'Unread'), ('R', 'Reading')], default='U', max_length=2),
        ),
    ]
