# Generated by Django 3.1.7 on 2021-04-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_libr', '0006_auto_20210329_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='user',
            field=models.OneToOneField(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='libuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='book',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='online_libr.book'),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='user',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='online_libr.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
