# Generated by Django 3.1.7 on 2021-04-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_libr', '0008_auto_20210405_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Planned'), ('C', 'Completed'), ('D', 'Dropped'), ('R', 'Reading')], default='U', max_length=2),
        ),
    ]
